version: '3'
services:
  achilis:
    image: "pankajchandan/achilis:latest"
    ports:
     - "3333:80"
  achcore:
    image: "pankajchandan/achcore:latest"
    ports:
     - "5000:80"
    volumes:
     - $HOME/core/logs:/logs
